name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: silex/emacs:29.1
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y make git
          
      - name: Generate exports
        run: |
          emacs --batch \
            --eval "(require 'ox-html)" \
            --eval "(require 'org)" \
            --eval "(dolist (f (directory-files-recursively \"./notes\" \"\\.org$\")) \
                     (with-current-buffer (find-file f) \
                       (org-html-export-to-html)))"
                       
      - name: Generate index
        run: |
          echo "# POPL 2025 Notes" > index.md
          echo "## Daily Notes" >> index.md
          for f in notes/*.html; do
            echo "* [$(basename $f .html)](${f})" >> index.md
          done
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
